/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LiquidityPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_PERCENTAGE"
      | "MINIMUM_LIQUIDITY"
      | "PRECISION"
      | "addLiquidity"
      | "collectFees"
      | "collectedFees0"
      | "collectedFees1"
      | "createPool"
      | "getLPPosition"
      | "getPoolInfo"
      | "getSwapAmount"
      | "lpPositions"
      | "nextPoolId"
      | "owner"
      | "pause"
      | "paused"
      | "pools"
      | "removeLiquidity"
      | "renounceOwnership"
      | "swap"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "OwnershipTransferred"
      | "Paused"
      | "PoolCreated"
      | "PoolFeeCollected"
      | "Swapped"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectedFees0",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectedFees1",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLPPosition",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapAmount",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lpPositions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPoolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pools", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLPPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSwapAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextPoolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    provider: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    sharesIssued: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    provider: string,
    amount0: bigint,
    amount1: bigint,
    sharesIssued: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    provider: string;
    amount0: bigint;
    amount1: bigint;
    sharesIssued: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    provider: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    sharesBurned: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    provider: string,
    amount0: bigint,
    amount1: bigint,
    sharesBurned: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    provider: string;
    amount0: bigint;
    amount1: bigint;
    sharesBurned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    token0: AddressLike,
    token1: AddressLike,
    initialLiquidity0: BigNumberish,
    initialLiquidity1: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    token0: string,
    token1: string,
    initialLiquidity0: bigint,
    initialLiquidity1: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    token0: string;
    token1: string;
    initialLiquidity0: bigint;
    initialLiquidity1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFeeCollectedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    fee0: BigNumberish,
    fee1: BigNumberish
  ];
  export type OutputTuple = [poolId: bigint, fee0: bigint, fee1: bigint];
  export interface OutputObject {
    poolId: bigint;
    fee0: bigint;
    fee1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwappedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    user: AddressLike,
    tokenIn: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    newReserve0: BigNumberish,
    newReserve1: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    user: string,
    tokenIn: string,
    amountIn: bigint,
    amountOut: bigint,
    newReserve0: bigint,
    newReserve1: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    user: string;
    tokenIn: string;
    amountIn: bigint;
    amountOut: bigint;
    newReserve0: bigint;
    newReserve1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidityPool extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityPool;
  waitForDeployment(): Promise<this>;

  interface: LiquidityPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  MINIMUM_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [poolId: BigNumberish, amount0: BigNumberish, amount1: BigNumberish],
    [void],
    "nonpayable"
  >;

  collectFees: TypedContractMethod<
    [poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  collectedFees0: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  collectedFees1: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  createPool: TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getLPPosition: TypedContractMethod<
    [user: AddressLike, poolId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        depositedToken0: bigint;
        depositedToken1: bigint;
      }
    ],
    "view"
  >;

  getPoolInfo: TypedContractMethod<
    [poolId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        token0: string;
        token1: string;
        reserve0: bigint;
        reserve1: bigint;
        totalShares: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getSwapAmount: TypedContractMethod<
    [poolId: BigNumberish, tokenIn: AddressLike, amountIn: BigNumberish],
    [bigint],
    "view"
  >;

  lpPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        poolId: bigint;
        shares: bigint;
        depositedToken0: bigint;
        depositedToken1: bigint;
      }
    ],
    "view"
  >;

  nextPoolId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pools: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        token0: string;
        token1: string;
        reserve0: bigint;
        reserve1: bigint;
        totalShares: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  removeLiquidity: TypedContractMethod<
    [poolId: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  swap: TypedContractMethod<
    [
      poolId: BigNumberish,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINIMUM_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [poolId: BigNumberish, amount0: BigNumberish, amount1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectedFees0"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "collectedFees1"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLPPosition"
  ): TypedContractMethod<
    [user: AddressLike, poolId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        depositedToken0: bigint;
        depositedToken1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [poolId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        token0: string;
        token1: string;
        reserve0: bigint;
        reserve1: bigint;
        totalShares: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSwapAmount"
  ): TypedContractMethod<
    [poolId: BigNumberish, tokenIn: AddressLike, amountIn: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        poolId: bigint;
        shares: bigint;
        depositedToken0: bigint;
        depositedToken1: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextPoolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        token0: string;
        token1: string;
        reserve0: bigint;
        reserve1: bigint;
        totalShares: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [poolId: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [
      poolId: BigNumberish,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolFeeCollected"
  ): TypedContractEvent<
    PoolFeeCollectedEvent.InputTuple,
    PoolFeeCollectedEvent.OutputTuple,
    PoolFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "Swapped"
  ): TypedContractEvent<
    SwappedEvent.InputTuple,
    SwappedEvent.OutputTuple,
    SwappedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PoolCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "PoolFeeCollected(uint256,uint256,uint256)": TypedContractEvent<
      PoolFeeCollectedEvent.InputTuple,
      PoolFeeCollectedEvent.OutputTuple,
      PoolFeeCollectedEvent.OutputObject
    >;
    PoolFeeCollected: TypedContractEvent<
      PoolFeeCollectedEvent.InputTuple,
      PoolFeeCollectedEvent.OutputTuple,
      PoolFeeCollectedEvent.OutputObject
    >;

    "Swapped(uint256,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
    Swapped: TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
