/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StreamPayCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "availableToClaim"
      | "cancelStream"
      | "claim"
      | "createStream"
      | "getStreamInfo"
      | "nextStreamId"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "streams"
      | "transferOwnership"
      | "unpause"
      | "withdrawExpiredStream"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "StreamCancelled"
      | "StreamClaimed"
      | "StreamCreated"
      | "StreamWithdrawn"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "availableToClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "createStream",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStreamInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextStreamId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streams",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawExpiredStream",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "availableToClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStreamInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextStreamId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "streams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawExpiredStream",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCancelledEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    sender: AddressLike,
    senderRefund: BigNumberish,
    recipientPayout: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    sender: string,
    senderRefund: bigint,
    recipientPayout: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    sender: string;
    senderRefund: bigint;
    recipientPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamClaimedEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCreatedEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    sender: AddressLike,
    recipient: AddressLike,
    token: AddressLike,
    ratePerSecond: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    streamId: bigint,
    sender: string,
    recipient: string,
    token: string,
    ratePerSecond: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    streamId: bigint;
    sender: string;
    recipient: string;
    token: string;
    ratePerSecond: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamWithdrawnEvent {
  export type InputTuple = [
    streamId: BigNumberish,
    sender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [streamId: bigint, sender: string, amount: bigint];
  export interface OutputObject {
    streamId: bigint;
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StreamPayCore extends BaseContract {
  connect(runner?: ContractRunner | null): StreamPayCore;
  waitForDeployment(): Promise<this>;

  interface: StreamPayCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  availableToClaim: TypedContractMethod<
    [streamId: BigNumberish],
    [bigint],
    "view"
  >;

  cancelStream: TypedContractMethod<
    [streamId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;

  createStream: TypedContractMethod<
    [
      recipient: AddressLike,
      token: AddressLike,
      deposit: BigNumberish,
      ratePerSecond: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getStreamInfo: TypedContractMethod<
    [streamId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        sender: string;
        recipient: string;
        token: string;
        deposit: bigint;
        ratePerSecond: bigint;
        startTime: bigint;
        stopTime: bigint;
        remainingBalance: bigint;
        active: boolean;
        claimableNow: bigint;
      }
    ],
    "view"
  >;

  nextStreamId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  streams: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        sender: string;
        recipient: string;
        token: string;
        deposit: bigint;
        ratePerSecond: bigint;
        startTime: bigint;
        stopTime: bigint;
        remainingBalance: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawExpiredStream: TypedContractMethod<
    [streamId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "availableToClaim"
  ): TypedContractMethod<[streamId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelStream"
  ): TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createStream"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      token: AddressLike,
      deposit: BigNumberish,
      ratePerSecond: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getStreamInfo"
  ): TypedContractMethod<
    [streamId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        sender: string;
        recipient: string;
        token: string;
        deposit: bigint;
        ratePerSecond: bigint;
        startTime: bigint;
        stopTime: bigint;
        remainingBalance: bigint;
        active: boolean;
        claimableNow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextStreamId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "streams"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        sender: string;
        recipient: string;
        token: string;
        deposit: bigint;
        ratePerSecond: bigint;
        startTime: bigint;
        stopTime: bigint;
        remainingBalance: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawExpiredStream"
  ): TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "StreamCancelled"
  ): TypedContractEvent<
    StreamCancelledEvent.InputTuple,
    StreamCancelledEvent.OutputTuple,
    StreamCancelledEvent.OutputObject
  >;
  getEvent(
    key: "StreamClaimed"
  ): TypedContractEvent<
    StreamClaimedEvent.InputTuple,
    StreamClaimedEvent.OutputTuple,
    StreamClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StreamCreated"
  ): TypedContractEvent<
    StreamCreatedEvent.InputTuple,
    StreamCreatedEvent.OutputTuple,
    StreamCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StreamWithdrawn"
  ): TypedContractEvent<
    StreamWithdrawnEvent.InputTuple,
    StreamWithdrawnEvent.OutputTuple,
    StreamWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "StreamCancelled(uint256,address,uint256,uint256)": TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;
    StreamCancelled: TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;

    "StreamClaimed(uint256,address,uint256)": TypedContractEvent<
      StreamClaimedEvent.InputTuple,
      StreamClaimedEvent.OutputTuple,
      StreamClaimedEvent.OutputObject
    >;
    StreamClaimed: TypedContractEvent<
      StreamClaimedEvent.InputTuple,
      StreamClaimedEvent.OutputTuple,
      StreamClaimedEvent.OutputObject
    >;

    "StreamCreated(uint256,address,address,address,uint256,uint256)": TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
    StreamCreated: TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;

    "StreamWithdrawn(uint256,address,uint256)": TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
    StreamWithdrawn: TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
