/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SwapRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS"
      | "CIRCUIT_BREAKER_THRESHOLD"
      | "MAX_SLIPPAGE_BPS"
      | "createRoute"
      | "emergencyWithdraw"
      | "estimateSwap"
      | "lastSwapTime"
      | "nextRouteId"
      | "oracles"
      | "owner"
      | "pause"
      | "paused"
      | "registerOracle"
      | "renounceOwnership"
      | "routes"
      | "swapExactInputMultiHop"
      | "swapExactInputSingle"
      | "swapRouter"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MultiHopSwapExecuted"
      | "OwnershipTransferred"
      | "Paused"
      | "PriceCircuitBreakerTriggered"
      | "RouteCreated"
      | "SwapExecuted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CIRCUIT_BREAKER_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SLIPPAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createRoute",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateSwap",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "lastSwapTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRouteId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracles", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerOracle",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInputMultiHop",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInputSingle",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CIRCUIT_BREAKER_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SLIPPAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastSwapTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRouteId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "routes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInputMultiHop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInputSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace MultiHopSwapExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    routeIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    routeIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    routeIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceCircuitBreakerTriggeredEvent {
  export type InputTuple = [
    token: AddressLike,
    currentPrice: BigNumberish,
    expectedPrice: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    token: string,
    currentPrice: bigint,
    expectedPrice: bigint,
    reason: string
  ];
  export interface OutputObject {
    token: string;
    currentPrice: bigint;
    expectedPrice: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteCreatedEvent {
  export type InputTuple = [
    routeIndex: BigNumberish,
    tokens: AddressLike[],
    fees: BigNumberish[]
  ];
  export type OutputTuple = [
    routeIndex: bigint,
    tokens: string[],
    fees: bigint[]
  ];
  export interface OutputObject {
    routeIndex: bigint;
    tokens: string[];
    fees: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwapRouter extends BaseContract {
  connect(runner?: ContractRunner | null): SwapRouter;
  waitForDeployment(): Promise<this>;

  interface: SwapRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS: TypedContractMethod<[], [bigint], "view">;

  CIRCUIT_BREAKER_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_SLIPPAGE_BPS: TypedContractMethod<[], [bigint], "view">;

  createRoute: TypedContractMethod<
    [tokens: AddressLike[], fees: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  estimateSwap: TypedContractMethod<
    [amountIn: BigNumberish, route: AddressLike[]],
    [bigint],
    "view"
  >;

  lastSwapTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  nextRouteId: TypedContractMethod<[], [bigint], "view">;

  oracles: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        priceFeed: string;
        decimals: bigint;
        stalePriceThreshold: bigint;
        lowerBoundPercent: bigint;
        upperBoundPercent: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerOracle: TypedContractMethod<
    [
      token: AddressLike,
      priceFeed: AddressLike,
      stalePriceThreshold: BigNumberish,
      lowerBound: BigNumberish,
      upperBound: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  routes: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  swapExactInputMultiHop: TypedContractMethod<
    [routeId: BigNumberish, amountIn: BigNumberish, minAmountOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  swapExactInputSingle: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      fee: BigNumberish,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  swapRouter: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CIRCUIT_BREAKER_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SLIPPAGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createRoute"
  ): TypedContractMethod<
    [tokens: AddressLike[], fees: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "estimateSwap"
  ): TypedContractMethod<
    [amountIn: BigNumberish, route: AddressLike[]],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastSwapTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextRouteId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracles"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        priceFeed: string;
        decimals: bigint;
        stalePriceThreshold: bigint;
        lowerBoundPercent: bigint;
        upperBoundPercent: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerOracle"
  ): TypedContractMethod<
    [
      token: AddressLike,
      priceFeed: AddressLike,
      stalePriceThreshold: BigNumberish,
      lowerBound: BigNumberish,
      upperBound: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "routes"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapExactInputMultiHop"
  ): TypedContractMethod<
    [routeId: BigNumberish, amountIn: BigNumberish, minAmountOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapExactInputSingle"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      fee: BigNumberish,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "MultiHopSwapExecuted"
  ): TypedContractEvent<
    MultiHopSwapExecutedEvent.InputTuple,
    MultiHopSwapExecutedEvent.OutputTuple,
    MultiHopSwapExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PriceCircuitBreakerTriggered"
  ): TypedContractEvent<
    PriceCircuitBreakerTriggeredEvent.InputTuple,
    PriceCircuitBreakerTriggeredEvent.OutputTuple,
    PriceCircuitBreakerTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "RouteCreated"
  ): TypedContractEvent<
    RouteCreatedEvent.InputTuple,
    RouteCreatedEvent.OutputTuple,
    RouteCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "MultiHopSwapExecuted(address,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      MultiHopSwapExecutedEvent.InputTuple,
      MultiHopSwapExecutedEvent.OutputTuple,
      MultiHopSwapExecutedEvent.OutputObject
    >;
    MultiHopSwapExecuted: TypedContractEvent<
      MultiHopSwapExecutedEvent.InputTuple,
      MultiHopSwapExecutedEvent.OutputTuple,
      MultiHopSwapExecutedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PriceCircuitBreakerTriggered(address,int256,int256,string)": TypedContractEvent<
      PriceCircuitBreakerTriggeredEvent.InputTuple,
      PriceCircuitBreakerTriggeredEvent.OutputTuple,
      PriceCircuitBreakerTriggeredEvent.OutputObject
    >;
    PriceCircuitBreakerTriggered: TypedContractEvent<
      PriceCircuitBreakerTriggeredEvent.InputTuple,
      PriceCircuitBreakerTriggeredEvent.OutputTuple,
      PriceCircuitBreakerTriggeredEvent.OutputObject
    >;

    "RouteCreated(uint256,address[],uint24[])": TypedContractEvent<
      RouteCreatedEvent.InputTuple,
      RouteCreatedEvent.OutputTuple,
      RouteCreatedEvent.OutputObject
    >;
    RouteCreated: TypedContractEvent<
      RouteCreatedEvent.InputTuple,
      RouteCreatedEvent.OutputTuple,
      RouteCreatedEvent.OutputObject
    >;

    "SwapExecuted(address,address,address,uint256,uint256,uint24,uint256)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
